### ISSUE TITLE
Investigate medal API presence

### ISSUE THREAD

**Issue by dend** [OpenSpartan/grunt#52]
https://gamecms-hacs-origin.svc.halowaypoint.com/hi/Waypoint/file/medals/metadata.json

**Comment by mdrago1026** [comment]
I saw this with their new stats on waypoint. I was trying to find a mapping of personal IDs -> english names. Besides manually mapping them (which I've done for vehicle boardings/destroys), I ave yet to find anything else.

**Comment by dend** [comment]
@mdrago1026 there is actually an approach to that - I'll document it.

**Comment by dend** [comment]
This is now implemented as of Grunt 0.1.9: https://gruntapi.com/blog/changelog-grunt-halo-infinite-api-0.1.9/

Guide coming soon, but the metadata endpoint should expose most of hte medal information that can then be mapped to the player service record.

**Comment by mdrago1026** [comment]
@dend  -- did you ever find a way to map the personal score ids to english names? 343 obviously surfaces which personal scores IDs you get, the count, and how many points awarded, but I can't find a mapping for these anywhere.

**Comment by dend** [comment]
@mdrago1026 see here: https://docs.gruntapi.com/articles/guides/medal-records.html
